service: subsidy-navi-backend

provider:
  name: aws
  runtime: python3.11
  stage: ${opt:stage, 'dev'}
  region: ap-northeast-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux